id: A7315C32C
title: An Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:29:37.815148
  last_modified_at: 2022-02-28 23:29:37.815156
